AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
Layout/DotPosition:
  EnforcedStyle: leading
  Enabled: true
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: single_quotes
