AllCops:
  TargetRubyVersion: 2.7
StringLiterals:
  EnforcedStyle: single_quotes
Documentation:
  Enabled: false
DotPosition:
  EnforcedStyle: leading
  Enabled: true
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
